version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tim-db
    restart: always
    environment:
      POSTGRES_USER: timuser
      POSTGRES_PASSWORD: timpass
      POSTGRES_DB: timshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
